# Generated by Django 3.2.25 on 2024-09-15 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recipe_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagAdmin',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.tag')),
            ],
            bases=('core.tag',),
        ),
    ]
