# Generated by Django 3.2.25 on 2024-09-19 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240919_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientAdmin',
            fields=[
                ('ingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ingredient')),
            ],
            bases=('core.ingredient',),
        ),
    ]
